# Generated by Django 4.1.5 on 2023-01-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuItemAPI', '0002_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('title',)},
        ),
    ]
