# Generated by Django 4.1.5 on 2023-01-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuItemAPI', '0004_order_alter_category_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='featured',
            field=models.BooleanField(db_index=True, default=1),
        ),
    ]
