# Generated by Django 4.1.5 on 2023-01-17 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MenuItemAPI', '0005_menuitem_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_crew',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
