# Generated by Django 4.1.5 on 2023-02-04 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MenuItemAPI', '0006_remove_order_delivery_crew_remove_order_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='MenuItemAPI.category'),
        ),
    ]
